version: "3.9"

services:
  fastapi:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app:/app
    env_file: ".env"
    command: uvicorn main:app --host ${HOST} --port ${PORT}
